### ISSUE TITLE
Todo App 요구명세서 작성

### ISSUE THREAD

**Issue by rockbell89** [rockbell89/project-todo-app#2]
### 만들고자 하는 기능이 무엇인가요?
- Todo CRUD
  - Todo 생성 기능
  - Todo 조회 기능
  - Todo 수정 기능
  - Todo 삭제 기능
  
### 해당 기능을 구현하기위한 할 일
- [ ] CRA 프로젝트 생성
- [ ] eslint / prettier 설정
- [ ] 레이아웃 / 컴포넌트 작업
- [ ] 메인 페이지 작업
- [ ] 상세 페이지 작업

### 예상 작업시간
8h
